fos_oauth_server:
    db_driver: orm
    client_class:        App\Client
    access_token_class:  App\AccessToken
    refresh_token_class: App\RefreshToken
    auth_code_class:     App\AuthCode
    service:
        user_provider: fos_user.user_provider.username