parameters:
    database_host: "%env(DATABASE_HOST)%"
    database_port: "%env(DATABASE_PORT)%"
    database_name: "%env(DATABASE_NAME)%"
    database_user: "%env(DATABASE_USER)%"
    database_password: "%env(DATABASE_PASSWORD)%"
    migrations_user: "%env(DATABASE_USER)%"
    migrations_password: "%env(DATABASE_PASSWORD)%"

doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        mapping_types:
            enum: string
        server_version: 5.7
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App

doctrine_migrations:
    dir_name: "%kernel.root_dir%/DoctrineMigrations"
    namespace: App\DoctrineMigrations
    table_name: migration_versions
    name: Application Migrations
    organize_migrations: false
                