security:
    erase_credentials: false
    encoders:
        FOS\UserBundle\Model\UserInterface:
            algorithm: argon2i
            memory_cost: 16384 # Amount in KiB. 16 MiB
            time_cost: 4 # Number of iterations
            threads: 8 # Number of parallel threads

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false

        oauth_auth:
            pattern:    ^/oauth/v2/auth|^/log
            simple_form:
                authenticator: App\Security\DoubleHashAuthenticator
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            logout:       true
            anonymous:    true
            context:  oauth

        api:
            pattern:    ^/api
            fos_oauth:  true
            stateless:  true

        index:
            pattern:    ^/
            anonymous:    true
            context:  oauth

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/admin/, role: ROLE_ADMIN }
        - { path: ^/api/, roles: ROLE_USER }
