controllers:
    resource: ../src/Controller/
    type: annotation
    prefix: /api

admin_controllers:
    resource: ../src/Controller/Admin/
    type: annotation
    prefix: /api/admin

index:
    path: /
    controller: App\Controller\DefaultController::index

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"


fos_user_security_login:
    path: /login 
    methods: [GET, POST]
    controller: "fos_user.security.controller:loginAction"

fos_user_security_check:
    path: /login_check 
    methods: [POST]
    controller: "fos_user.security.controller:checkAction"

fos_user_security_logout:
    path: /logout 
    methods: [GET, POST]
    controller: "fos_user.security.controller:logoutAction"

